FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IG9wZW5zaGlmdC1hY21lLWluc3RhbGxlcgpkZXNjcmlwdGlvbjog\
QW4gQVBCIHRoYXQgZGVwbG95cyB0aGUgT3BlblNoaWZ0IEFDTUUgQ29udHJvbGxlcgpiaW5kYWJs\
ZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBvcGVuc2hp\
ZnQtYWNtZS1pbnN0YWxsZXIKcGxhbnM6CiAgLSBuYW1lOiBkZWZhdWx0CiAgICBkZXNjcmlwdGlv\
bjogVGhpcyBkZWZhdWx0IHBsYW4gZGVwbG95cyBvcGVuc2hpZnQtYWNtZQogICAgZnJlZTogVHJ1\
ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJhbWV0ZXJzOiBbXQo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
