- k8s_v1_service:
    name: acme-controller
    namespace: '{{ namespace }}'
    state: absent

- openshift_v1_cluster_role_binding:
    name: acme-controller
    namespace: '{{ namespace }}'
    state: absent

- openshift_v1_cluster_role:
    name: acme-controller
    state: absent

- k8s_v1_service_account:
    name: acme-controller
    namespace: '{{ namespace }}'
    state: absent

- openshift_v1_deployment_config:
    name: acme-controller
    namespace: '{{ namespace }}'
    state: absent

- openshift_v1_project:
    name: '{{ namespace }}'
    state: absent
